# Generated by Django 4.2 on 2023-09-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homehireupload',
            old_name='pic',
            new_name='images',
        ),
    ]
