# Generated by Django 4.2 on 2023-09-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0002_rename_pic_homehireupload_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homehire',
            old_name='images',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='homehireupload',
            name='images',
        ),
        migrations.AddField(
            model_name='homehireupload',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='homehireupload',
            name='homeHire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realEstate.homehire'),
        ),
    ]
