# Generated by Django 4.2 on 2023-09-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0006_alter_homesale_mabds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='makh',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mahost',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
