# Generated by Django 4.2 on 2023-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0010_customer_phonendd_customer_representativename'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cmnd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cmndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='placeCmnd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
