# Generated by Django 4.2 on 2023-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0012_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesale',
            name='altar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='packArea',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='pool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='post_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='post_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='productOf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homesale',
            name='twoFace',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
