# Generated by Django 4.2 on 2023-10-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0013_homesale_altar_homesale_garden_homesale_packarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homehire',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='homesale',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
